---
- hosts: docker
  become: true

  vars:
    docker_users:
      - localadmin
      - vincent

  roles:
    - geerlingguy.docker
    # - ericsysmin.docker

  tasks:
    - name: Checking docker version
      shell: docker version
      changed_when: false
