---
- hosts: k8s_control_plane
  become: true

  roles:
    - andrewrothstein.rke
    - gantsign.helm

  tasks:
    - name: Checking rke version
      shell: /usr/local/bin/rke --version
      changed_when: false

    - name: Checking helm version
      shell: /usr/local/bin/helm version
      changed_when: false
